<hr color="magenta" size="5">

*   <font color="cyan" size="5">The Code Using NN Module is in the Bottom of this notebook</font>


## Data Preprocessing

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()# Scaling TheData
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.24544533, -0.14133728, -0.2186462 , ...,  1.53049503,
         1.70882335,  1.9928296 ],
       [-0.33469162, -1.41581195, -0.35135148, ...,  0.06935838,
        -0.84239415,  0.13339557],
       [-0.74637613, -0.46353593, -0.7360288 , ..., -0.73685078,
        -0.50290407, -0.12911953],
       ...,
       [-1.67079496,  0.34554068, -1.5923138 , ..., -0.5055433 ,
         0.73741116,  3.75633362],
       [-0.71470809, -1.1485064 , -0.69445342, ..., -0.65604194,
        -0.93146828, -0.10729114],
       [-0.68016114, -0.52081569, -0.73434899, ..., -1.07198824,
        -0.25584941, -0.85922168]])

In [ ]:
y_train

47     M
322    B
142    B
112    B
519    B
      ..
124    B
96     B
151    B
540    B
350    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,

### Numpy to Pytorch Tensor

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

# A simple Nural Network Without PyTorch Library

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [ ]:
learning_rate = 0.1
epochs = 50

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.3597768311929963
Epoch: 2, Loss: 3.2256940582226914
Epoch: 3, Loss: 3.087920698887518
Epoch: 4, Loss: 2.947444598743172
Epoch: 5, Loss: 2.8002911785936764
Epoch: 6, Loss: 2.647806234278138
Epoch: 7, Loss: 2.4946535025166803
Epoch: 8, Loss: 2.33774442564648
Epoch: 9, Loss: 2.176121893506261
Epoch: 10, Loss: 2.0129883807644604
Epoch: 11, Loss: 1.8565051992766728
Epoch: 12, Loss: 1.7068364082384646
Epoch: 13, Loss: 1.5633258842585658
Epoch: 14, Loss: 1.4308949539018725
Epoch: 15, Loss: 1.3094744768025053
Epoch: 16, Loss: 1.1993934659562895
Epoch: 17, Loss: 1.1048607437287157
Epoch: 18, Loss: 1.0263391669456232
Epoch: 19, Loss: 0.9633065448452306
Epoch: 20, Loss: 0.9141435456692392
Epoch: 21, Loss: 0.8764160929763533
Epoch: 22, Loss: 0.8474501396553444
Epoch: 23, Loss: 0.824859006286696
Epoch: 24, Loss: 0.8067971441864763
Epoch: 25, Loss: 0.7919624810550108
Epoch: 26, Loss: 0.7794783458920238
Epoch: 27, Loss: 0.7687606244969305
Epoch: 28, Loss: 0.7594145793590029
Epoch: 2

In [ ]:
model.bias

tensor([-0.3873], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5438596606254578


<hr color="cyan" size="2">

# <font color="lightblue"> Now Defining the same model using PyTorch Packages


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim


X_train_tensor = X_train_tensor.to(torch.float)
y_train_tensor = y_train_tensor.to(torch.float)
X_test_tensor = X_test_tensor.to(torch.float)
y_test_tensor = y_test_tensor.to(torch.float)



# Define the model
class MySimpleNN(nn.Module):
    def __init__(self, input_dim):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(input_dim, 1)

    def forward(self, X):
        z = self.linear(X)
        y_pred = torch.sigmoid(z)
        return y_pred


learning_rate = 0.1
epochs = 50

# Create the model
input_dim = X_train_tensor.shape[1]
model = MySimpleNN(input_dim).to(torch.float)


criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):

    y_pred = model(X_train_tensor).squeeze()

    loss = criterion(y_pred, y_train_tensor)

    optimizer.zero_grad()
    loss.backward()

    optimizer.step()

    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

# Model evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')


Epoch: 1, Loss: 0.9974225163459778
Epoch: 2, Loss: 0.7107337117195129
Epoch: 3, Loss: 0.556262731552124
Epoch: 4, Loss: 0.46771764755249023
Epoch: 5, Loss: 0.4106990396976471
Epoch: 6, Loss: 0.37064027786254883
Epoch: 7, Loss: 0.34072160720825195
Epoch: 8, Loss: 0.3173578679561615
Epoch: 9, Loss: 0.29848793148994446
Epoch: 10, Loss: 0.2828439772129059
Epoch: 11, Loss: 0.26960262656211853
Epoch: 12, Loss: 0.2582056522369385
Epoch: 13, Loss: 0.24826057255268097
Epoch: 14, Loss: 0.2394828498363495
Epoch: 15, Loss: 0.23166079819202423
Epoch: 16, Loss: 0.22463341057300568
Epoch: 17, Loss: 0.21827548742294312
Epoch: 18, Loss: 0.21248841285705566
Epoch: 19, Loss: 0.20719292759895325
Epoch: 20, Loss: 0.20232458412647247
Epoch: 21, Loss: 0.19783033430576324
Epoch: 22, Loss: 0.19366604089736938
Epoch: 23, Loss: 0.18979452550411224
Epoch: 24, Loss: 0.18618425726890564
Epoch: 25, Loss: 0.18280822038650513
Epoch: 26, Loss: 0.17964321374893188
Epoch: 27, Loss: 0.17666897177696228
Epoch: 28, Loss: 0.